-
  name: configuration frontend
  hosts: frontend
  become: yes
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: status SELinux
      shell: "sestatus"
      register: status_SELinux
    - debug:
        msg: " {{status_SELinux.stdout_lines}}"

    - name: be sure firewalld is installed
      dnf: name=firewalld state=installed


    - name: be sure firewalld is disabled
      systemd: name=firewalld enabled=no


    - name: be sure firewalld is stopped
      systemd: name=firewalld state=stopped
      ignore_errors: yes

    - name: Install Nginx Web Server
      yum:
        name=nginx
        state=latest
      notify:
        - nginx systemd
    - name: configure NGINX
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: 'location / {'
        line: "         proxy_pass http://192.168.5.152:19999;"
    - name: restart nginx
      service:
         name: nginx
         state: restarted
-
  name: configuration backend
  hosts: backend
  become: yes
  tasks:
    - name: To install NetData
      apt:
        name: [ 'git', 'zlib1g-dev', 'uuid-dev', 'libmnl-dev', 'pkg-config', 'curl', 'gcc', 'make', 'autoconf', 'autoconf-archive', 'autogen', 'automake', 'lm-sensors', 'netcat', 'nodejs', 'libuv1-dev', 'zlib1g-dev' ]
        update_cache: yes
        state: present
    - name:
      git:
          repo: 'https://github.com/firehol/netdata.git'
          dest: /opt/netdata/
          clone: yes
          update: yes
    - name: to run the shell script
      shell: bash netdata-installer.sh --dont-wait --libs-are-really-here
      args:
           chdir: /opt/netdata
  handlers:
    - name: to restart netdata
      service:
        name: netdata
        state: restarted