-
  name: configuration frontend
  hosts: frontend
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: be sure firewalld is installed
      dnf: name=firewalld state=installed
      tags:
       - install
       - firewalld
    - name: be sure firewalld is disabled
      systemd: name=firewalld enabled=no
      tags:
        - install
        - atomic
        - firewalld
    - name: be sure firewalld is stopped
      systemd: name=firewalld state=stopped
      ignore_errors: yes
      tags:
       - install
       - atomic
       - firewalld
-
  name: configuration backend
  hosts: backend
  become: yes
  tasks:
       - name: To install NetData
         apt:
           name: [ 'git', 'zlib1g-dev', 'uuid-dev', 'libmnl-dev', 'pkg-config', 'curl', 'gcc', 'make', 'autoconf', 'autoconf-archive', 'autogen', 'automake', 'python', 'python-yaml',
                   'python-mysqldb', 'lm-sensors', 'python-psycopg2', 'netcat', 'nodejs', 'libuv1-dev', 'zlib1g-dev' ]
           update_cache: yes
           state: present

       - name: git
         git:
           repo: 'https://github.com/firehol/netdata.git'
           dest: /opt/netdata/
           clone: yes
           update: yes
       - name: to run the shell script
         shell: bash netdata-installer.sh --dont-wait --libs-are-really-here
         args:
           chdir: /opt/netdata
  handlers:
       - name: to restart netdata
         service:
           name: netdata
           state: restarted